#ifndef GPIO_PINS
#define GPIO_PINS

#define MOTOR_RIGHT_1 20
#define MOTOR_RIGHT_2 21
#define MOTOR_ENABLE_1 18

#define MOTOR_LEFT_1 22
#define MOTOR_LEFT_2 23
#define MOTOR_ENABLE_2 19

#define ULTRASONIC_R_TRIG 28
#define ULTRASONIC_R_ECHO 31

#define HALL_EFFECT_1_H 8
#define HALL_EFFECT_1_L 9
#define HALL_EFFECT_2_H 10
#define HALL_EFFECT_2_L 11

#endif // GPIO_PINS
